### ISSUE TITLE
Cannot generate controller from cli

### ISSUE THREAD

**Issue by AceHack** [dotnet/Scaffolding#1347]
When running  `dotnet aspnet-codegenerator controller -name AuthorController -async -api -m Author -dc MyDbContext -outDir Controller`

I get the following error
```
Building project ...
Finding the generator 'controller'...
No code generators found with the name 'controller'
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGeneratorsLocator.GetCodeGenerator(String codeGeneratorName)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
RunTime 00:00:04.23
```
## Steps to reproduce:
run `dotnet aspnet-codegenerator controller -name AuthorController -async -api -m Author -dc MyDbContext -outDir Controller`

Here is my csproj
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <UserSecretsId>xxx</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="3.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.1.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="3.1.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.10.9" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.3" />
  </ItemGroup>

</Project>
```

Here is my dotnet-tools.json
```
{
  "version": 1,
  "isRoot": true,
  "tools": {
    "dotnet-ef": {
      "version": "3.1.4",
      "commands": [
        "dotnet-ef"
      ]
    },
    "dotnet-aspnet-codegenerator": {
      "version": "3.1.3",
      "commands": [
        "dotnet-aspnet-codegenerator"
      ]
    }
  }
}
```

## Expected behavior:
Controller to be created

## Actual behavior:
Failure
```
Building project ...
Finding the generator 'controller'...
No code generators found with the name 'controller'
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGeneratorsLocator.GetCodeGenerator(String codeGeneratorName)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
RunTime 00:00:04.23
```

### Target framework(s):
netcoreapp3.1

### Package version of Microsoft.AspNetCore.App or Microsoft.AspNetCore.All (if applicable):
Not manually selected

### Package version of Microsoft.VisualStudio.Web.CodeGeneration.Design - this may be added to your project by scaffolding:
3.1.3

**Comment by AceHack** [comment]
The problem appears to be caused by installing the latest dotnet core SDK 3.1.400-preview-015151 that comes with the latest VS 2019 16.7 Preview 2.  Rolling back to SDK 3.1.300 appears to have fixed the issue.

**Comment by bravecobra** [comment]
I seem to have hit the same problem.

**Comment by Rick-Anderson** [comment]
@AceHack  this doesn't repo with the current released 3.1 SDK. Can you close this issue?

**Comment by AceHack** [comment]
Where is the place to file bugs on preview releases?

**Comment by AceHack** [comment]
It is the current preview version.

**Comment by deepchoudhery** [comment]
I have looked at the issue it will be fixed in an upcoming servicing update(version 3.1.4)

**Comment by BrunoBlanes** [comment]
Is this by any chance the cause of the Visual Studio error "Import 'Microsoft.WebTools.Scaffolding.Core.ScaffolderFactory.FactoryConfigEvaluator' could not be satisfied." when trying to Scaffold Identity on a Blazor application?

**Comment by deepchoudhery** [comment]
@BrunoBlanes I don't think so but I am seeing that error pop up for other users as well. I'm digging into what is causing it. Would you mind opening another issue here and I can get more info off of you.

**Comment by BrunoBlanes** [comment]
@deepchoudhery it is done as #1364

**Comment by deepchoudhery** [comment]
Fixed in 3.1.4. Closing.

**Comment by mantovanig** [comment]
I still have the same problem.

Visual Studio Mac - 8.7.8
SDK 3.1.402

I'm trying to generate an API Controller using Entity Framework

`Running /Users/mantovanig/projects/test-net-core/test-net-core/obj/dotnet-aspnet-codegenerator --configuration "Debug" --project "/Users/mantovanig/projects/test-net-core/test-net-core/test-net-core.csproj" controller --model TodoItem --dataContext TodoContext -name TodoController --no-build -outDir "/Users/mantovanig/projects/test-net-core/test-net-core/Controllers" --controllerNamespace test_net_core.Controllers --restWithNoViews  --useSqlite 
Finding the generator 'controller'...
No code generators found with the name 'controller'
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGeneratorsLocator.GetCodeGenerator(String codeGeneratorName)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
RunTime 00:00:02.80

No code generators found with the name 'controller'`

**Comment by VGerris** [comment]
I wonder why this is closed, 3.1.4 is broken : https://github.com/dotnet/Scaffolding/issues/1387 .

**Comment by gvitola** [comment]
I am facing the same with .NET 5.0 and the package version 5.0.1. Any idea how to fix it?

**Comment by TB-Development** [comment]
1.  Add a global.json to specify your sdk version.

`dotnet new globaljson --sdk-version 3.1.300`

3.  Change your target framework in csproj file to (specify .NET version)

```
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

```
4.  Remove the newest version of CodeGeneration installed by default (without version number)

`dotnet remove package Microsoft.VisualStudio.Web.CodeGeneration.Design`

5.  Add a different, stable version back

`dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design -v 3.1.0`

`dotnet restore`
`dotnet build`

**Comment by mhoc4** [comment]
> 1. Add a global.json to specify your sdk version.
> 
> `dotnet new globaljson --sdk-version 3.1.300`

step 1 fixed it for me, sdk version 3.0

**Comment by ChristianFigueredo** [comment]
I fixed it updating the codegenator package:

* unistall codegenerator:

`dotnet tool uninstall --global dotnet-aspnet-codegenerator`

* install codegenerator (use your sdk version)

`dotnet tool install --global dotnet-aspnet-codegenerator --version 3.1.4`

* Restore
`dotnet restore`

**Comment by gvitola** [comment]
Thank you! Now it is working.

**Comment by backnotprop** [comment]
For mac users, and targeting `net5.0` try this stack overflow answer:

https://stackoverflow.com/questions/63584060/aspnet-codegenerator-no-code-generators-available-even-after-adding-microsoft

<hr/>
1. update global tools:
```
  dotnet tool install --global dotnet-aspnet-codegenerator
  dotnet tool update --global dotnet-aspnet-codegenerator
  dotnet tool install --global dotnet-ef
  dotnet tool update --global dotnet-ef
```

2. add/update links to packages
```
  dotnet remove package Microsoft.VisualStudio.Web.CodeGeneration.Design
  dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design
  dotnet add package Microsoft.EntityFrameworkCore.Design
```
2. Replace string `netcoreapp3.1.4` to `net5.0` in .csproj and launch.json files
3. Clear directories
    - bin
    - obj
5. Rebuild project
6. Finally run: 
```  
  dotnet aspnet-codegenerator --help
```
 If all fine it will show available generators.
