### ISSUE TITLE
Visual Studio Scaffolding features fail more often than they succeed; and no meaningful error messages

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/Scaffolding#1601]
### Describe the bug
I have found that the *Add |  New Scaffolder Item | Razor Pages using Entity Framework (CRUD)* command fails more often that it succeeds. In fact, I'd say it fails initially close to 80% of the time. Sometimes I can resolve it, other times I cannot.

Please, Please PLEASE, can't you give us some meaningful error messages here?!?

### To Reproduce
In my current case, I'm accessing this command by right clicking the *Pages* folder under one of my *Areas* folders. I select my model and data context classes.

![Untitled](https://user-images.githubusercontent.com/3191331/125654817-e412ef80-cc66-42ec-a118-370c81c00c2b.png)

But when I click *Add*, it churns for a few moments and then I get an error.

![Untitled](https://user-images.githubusercontent.com/3191331/125654951-ceb5325d-fef1-4ee6-b4fb-9e92b636bfb4.png)

*Package restore failed* is just not meaningful for me. What does it mean to restore a package here? And, more important, which package is failing? Without a meaningful error message, it sort of leaves me stuck.

### Include the output of `dotnet --info`

.NET SDK (reflecting any global.json):
 Version:   5.0.301
 Commit:    ef17233f86

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.301\

Host (useful for support):
  Version: 5.0.7
  Commit:  556582d964

.NET SDKs installed:
  5.0.301 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

### The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

16.10.3

**Comment by SoftCircuits** [comment]
So, the workaround was to manually add these pages myself and not bother with Visual Studio scaffolding code.

But today, I needed to add Identity scaffolding. The first time I tried, I got an error immediately.

> There was an error running the selected code generator:
> 
> 'Install the package Microsoft.VisualStudio.Web.CodeGeneration.Design and try again.'

I checked and this package was already at the current version. So I didn't change anything. But I tried it again and this time I got the same error as I got in my first post. Unfortunately, in this case there is not a manual workaround.

Again, these features are unreliable and fail more than they succeed. And, again, please Please PLEASE give us meaningful errors! Doesn't look like Microsoft is responding to any of this. So without meaningful errors, I'm blocked.

**Comment by deepchoudhery** [comment]
Hey, @SoftCircuits, we had an issue with config being not up to date. We have updated it since OTA. Would you let me know if it still keeps happening?

**Comment by deepchoudhery** [comment]
There is still an ongoing issue with the 'Install the package Microsoft.VisualStudio.Web.CodeGeneration.Design and try again.' I have an open issue tracking that and will be working on fixing that in the next lil bit. Will update you here as well. The health of the scaffolding scenario is a big priority for me so let me know if anything pops up.

**Comment by SoftCircuits** [comment]
> Hey, @SoftCircuits, we had an issue with config being not up to date. We have updated it since OTA. Would you let me know if it still keeps happening?

Thanks for responding. I'm not sure what it is but I just seem to have many different problems with this, and the error messages are generally not helpful.

So, I have updated to the latest version of Visual Studio and I tried adding Identity scaffolding again. This time, I get a different error.

![image](https://user-images.githubusercontent.com/3191331/126498554-10ef99c4-6bd3-495b-ac6d-fae1839bbe6c.png)

**Comment by awdorrin** [comment]
I've been running into similar errors trying to use the API Scaffolder with Entity Framework.
What it looks like to me, is that from the menu (or the Package Manager Console) that it cannot locate the .csproj file.
I could get things working from the Package Manager Console by moving down into the project folder then executing the command:
Ex:

- cd MyProj-App
- dotnet aspnet-codegenerator controller -name MyTestController -m MyTest -dc MainDBContext --relativeFolderPath Controllers -api --controllerNamespace MyProj.Controllers

I had to add the controllerNamespace, because existing controllers are defined as 'MyProj.Controllers' and the generator wanted to use 'MyProj-App.Controllers' (joys of maintaining legacy code) :-)

Hope this helps narrow down the issue

**Comment by SoftCircuits** [comment]
@awdorrin I'm not sure if I followed all that. Since I'm using Razor Pages, there are no controllers. Can you explain why you think it cannot locate the project file?

**Comment by awdorrin** [comment]
@SoftCircuits I have been seeing the same exact error message when trying to create API Controllers using Entity Framework.
_(There was an error running the selected code generator: 'Package restore failed. Rolling back package changes for 'Project')_

Since no errors were showing up in the console, I tried to use the command line instead, in hopes of seeing additional error context. When I did this, the first error I saw was about not being able to find the project file. 
It was then that I saw that the current directory in the 'Package Manager Console' window was the Solution folder, not the Project folder. After switching the the project folder, and re-running the command line, it worked.

This tells me that the packages are good with my install, and that the error message being displayed from the context menus is probably the wrong error message.

I did some googling, but cannot see how to change the 'current directory' for visual studio itself. Older VS versions had a configuration properties page where you could set ProjectDir instead of SolutionDir.

I bet if you ran the command: **dotnet aspnet-codegenerator razorpage** {with whatever options you need}
That the scaffolding would work for you

**Comment by SoftCircuits** [comment]
@awdorrin I'm not sure what options I need but I just tried this again today, and it worked! Nothing has changed so I don't know why. Like I said at the very start: My experience is that these scaffolding features are very unreliable and fail for me more often than they work.

**Comment by upizs** [comment]
@SoftCircuits Hi! Did you included your DbContext in the command. I had difficulty scaffolding in my project, where other project was doing fine. So I had to use the `dotnet aspnet-codegenerator` 
I advice to use this commands in the command line in your project folder. 
`dotnet tool install -g dotnet-aspnet-codegenerator`
and then you can run
`dotnet aspnet-codegenerator identity -dc MyApplication.Data.ApplicationDbContext --files "Account.Register;Account.Login"`
-dc showing path to your application context and --files if you want just specific files, but I just run without it and then deleted the pages I didn't want. 
Hope it helps.

**Comment by SoftCircuits** [comment]
@upizs I definitely included my DbContext class. I've been programming since the DOS days. So I kind of prefer interactive dialogs these days instead of command lines. Still seems like those should work.

**Comment by ZiCold** [comment]
@upizs Thank you for your answer! I didn't even read what --files means -_-
In the end it required Microsoft.AspNetCore.Identity.UI to install. But besides that it worked. This is the final command:
dotnet aspnet-codegenerator controller -name CustomerController -m Customer -dc ApplicationDbContext --relativeFolderPath Controllers --useDefaultLayout

It created controller and all CRUD views for it. It is enough. As for MSVS menu option I've reported to MSVS support:
https://developercommunity.visualstudio.com/t/error-with-scaffolding-datamodel-for-aspnet/1515437
But I do not think that they will touch it in the near future.

**Comment by SoftCircuits** [comment]
@ZiCold I really hate to use the command line version for this when Microsoft has developed perfectly good dialog boxes, but I keep hitting this issue.

How are you running this command? On the command line, or within Package Manager Console?

**Comment by SoftCircuits** [comment]
Since we can't have scaffolding. Could there be a place where we can manually download the current files and copy them into our project?

**Comment by deepchoudhery** [comment]
The templates exist [here](https://github.com/dotnet/Scaffolding/tree/main/src/Scaffolding/VS.Web.CG.Mvc/Templates/Identity). 
I apologize again I am working to resolve issues with scaffolding on VS. Will keep you updated when a fix goes out.

**Comment by SoftCircuits** [comment]
> The templates exist [here]

Thanks!

**Comment by grenadin** [comment]
@SoftCircuits I found this bug everytimes. But If you create Folder "Data" in your Project and use new scaffolding again. it almost success around 80%.

**Comment by vijayrkn** [comment]
This issue is fixed in the latest 6.0 version of the package.

**Comment by nguyentuananh921** [comment]
I still facing the same problem when adding Identity 
![image](https://github.com/dotnet/Scaffolding/assets/18616693/134e01eb-2a2b-455f-ac61-ed52ced24306)

.NET SDK:
 Version:   8.0.100-preview.7.23376.3
 Commit:    daebeea8ea

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-preview.7.23376.3\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-preview.7.23375.6
  Architecture: x64
  Commit:       65b696cf5e
  RID:          win-x64

.NET SDKs installed:
  7.0.305 [C:\Program Files\dotnet\sdk]
  8.0.100-preview.6.23330.14 [C:\Program Files\dotnet\sdk]
  8.0.100-preview.7.23376.3 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.6.23329.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.7.23375.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.6.23329.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.7.23375.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.6.23329.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.7.23376.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by chromium1** [comment]
Downloaded Visual Studio Community 2022 17.8.1
Started following tutorial to build the Razor Pages Movies web application.
Got stuck here: Part 2, add a model to a Razor Pages app in ASP.NET Core
Complete the Add Razor Pages using Entity Framework (CRUD) dialog:
---------------------------
Microsoft Visual Studio
---------------------------
Error

There was an error running the selected code generator:

'Package restore failed. Rolling back package changes for 'RazorPagesMovie'.'
---------------------------
OK   
---------------------------

**Comment by JimiC** [comment]
Faced the same issue and had it working after installing manually the `Microsoft.VisualStudio.Web.CodeGeneration.Design` package from `nuget.org`.
