### ISSUE TITLE
dotnet-aspnet-codegenerator razorpage - "The type or namespace name 'Pages' does not exist in the namespace..."

### ISSUE THREAD

**Issue by dharmatech** [dotnet/Scaffolding#1661]
Here's an ASP.NET Core tutorial from the Microsoft docs:

https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/?view=aspnetcore-6.0

# Example which works

The following PowerShell script setups up a new project based on that tutorial:

```PowerShell
cd ~\tmp

dotnet new webapp --output MoviesNet6

cd MoviesNet6

mkdir Models

Set-Content .\Models\Movie.cs @"
using System;
using System.ComponentModel.DataAnnotations;

namespace MoviesNet6.Models
{
    public class Movie
    {
        public int ID { get; set; }
        public string Title { get; set; }

        [DataType(DataType.Date)]
        public DateTime ReleaseDate { get; set; }
        public string Genre { get; set; }
        public decimal Price { get; set; }
    }
}
"@


dotnet tool uninstall -g dotnet-aspnet-codegenerator
dotnet tool install -g dotnet-aspnet-codegenerator --version 6.0.0-rc.1.21464.1
dotnet tool uninstall -g dotnet-ef
dotnet tool install --global dotnet-ef --version 6.0.0-rc.1.21452.10
dotnet add package Microsoft.EntityFrameworkCore.Design --prerelease
dotnet add package Microsoft.EntityFrameworkCore.SQLite --prerelease
dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design --prerelease
dotnet add package Microsoft.EntityFrameworkCore.SqlServer --prerelease


dotnet-aspnet-codegenerator razorpage -m Movie -dc RazorPagesMovieContext -udl -outDir Pages\Movies --referenceScriptLibraries -sqlite

dotnet build
```

It works fine.

# Example demonstrating the issue

Now, instead of calling the project `MoviesNet6`, let's call it `Movies`. Here's the same PowerShell script updated accordingly:

```
cd ~\tmp

dotnet new webapp --output Movies

cd .\Movies

mkdir Models

Set-Content .\Models\Movie.cs @"
using System;
using System.ComponentModel.DataAnnotations;

namespace Movies.Models
{
    public class Movie
    {
        public int ID { get; set; }
        public string Title { get; set; }

        [DataType(DataType.Date)]
        public DateTime ReleaseDate { get; set; }
        public string Genre { get; set; }
        public decimal Price { get; set; }
    }
}
"@


dotnet tool uninstall -g dotnet-aspnet-codegenerator
dotnet tool install -g dotnet-aspnet-codegenerator --version 6.0.0-rc.1.21464.1
dotnet tool uninstall -g dotnet-ef
dotnet tool install --global dotnet-ef --version 6.0.0-rc.1.21452.10
dotnet add package Microsoft.EntityFrameworkCore.Design --prerelease
dotnet add package Microsoft.EntityFrameworkCore.SQLite --prerelease
dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design --prerelease
dotnet add package Microsoft.EntityFrameworkCore.SqlServer --prerelease


dotnet-aspnet-codegenerator razorpage -m Movie -dc RazorPagesMovieContext -udl -outDir Pages\Movies --referenceScriptLibraries -sqlite

dotnet build
```

# Error messages

This time, the project does not build. The following errors are shown:

```
C:\Users\dharm\tmp\Movies\Microsoft.NET.Sdk.Razor.SourceGenerators\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Pages_Movies_Create_cshtml.g.cs(413,78): error CS0234: The type or namespace name 'Pages' does not exist in the namespace 'Movies.Pages.Movies' (are you missing an assembly reference?) [C:\Users\dharm\tmp\Movies\Movies.csproj]
C:\Users\dharm\tmp\Movies\Microsoft.NET.Sdk.Razor.SourceGenerators\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Pages_Movies_Delete_cshtml.g.cs(198,78): error CS0234: The type or namespace name 'Pages' does not exist in the namespace 'Movies.Pages.Movies' (are you missing an assembly reference?) [C:\Users\dharm\tmp\Movies\Movies.csproj]
C:\Users\dharm\tmp\Movies\Microsoft.NET.Sdk.Razor.SourceGenerators\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Pages_Movies_Edit_cshtml.g.cs(437,78): error CS0234: The type or namespace name 'Pages' does not exist in the namespace 'Movies.Pages.Movies' (are you missing an assembly reference?) [C:\Users\dharm\tmp\Movies\Movies.csproj]
C:\Users\dharm\tmp\Movies\Microsoft.NET.Sdk.Razor.SourceGenerators\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Pages_Movies_Create_cshtml.g.cs(414,88): error CS0234: The type or namespace name 'Pages' does not exist in the namespace 'Movies.Pages.Movies' (are you missing an assembly reference?) [C:\Users\dharm\tmp\Movies\Movies.csproj]
C:\Users\dharm\tmp\Movies\Microsoft.NET.Sdk.Razor.SourceGenerators\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Pages_Movies_Delete_cshtml.g.cs(199,88): error CS0234: The type or namespace name 'Pages' does not exist in the namespace 'Movies.Pages.Movies' (are you missing an assembly reference?) [C:\Users\dharm\tmp\Movies\Movies.csproj]
C:\Users\dharm\tmp\Movies\Microsoft.NET.Sdk.Razor.SourceGenerators\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Pages_Movies_Details_cshtml.g.cs(184,78): error CS0234: The type or namespace name 'Pages' does not exist in the namespace 'Movies.Pages.Movies' (are you missing an assembly reference?) [C:\Users\dharm\tmp\Movies\Movies.csproj]
C:\Users\dharm\tmp\Movies\Microsoft.NET.Sdk.Razor.SourceGenerators\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Pages_Movies_Create_cshtml.g.cs(415,23): error CS0234: The type or namespace name 'Pages' does not exist in the namespace 'Movies.Pages.Movies' (are you missing an assembly reference?) [C:\Users\dharm\tmp\Movies\Movies.csproj]
C:\Users\dharm\tmp\Movies\Microsoft.NET.Sdk.Razor.SourceGenerators\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Pages_Movies_Index_cshtml.g.cs(264,78): error CS0234: The type or namespace name 'Pages' does not exist in the namespace 'Movies.Pages.Movies' (are you missing an assembly reference?) [C:\Users\dharm\tmp\Movies\Movies.csproj]
C:\Users\dharm\tmp\Movies\Microsoft.NET.Sdk.Razor.SourceGenerators\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Pages_Movies_Edit_cshtml.g.cs(438,88): error CS0234: The type or namespace name 'Pages' does not exist in the namespace 'Movies.Pages.Movies' (are you missing an assembly reference?) [C:\Users\dharm\tmp\Movies\Movies.csproj]
C:\Users\dharm\tmp\Movies\Microsoft.NET.Sdk.Razor.SourceGenerators\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Pages_Movies_Delete_cshtml.g.cs(200,23): error CS0234: The type or namespace name 'Pages' does not exist in the namespace 'Movies.Pages.Movies' (are you missing an assembly reference?) [C:\Users\dharm\tmp\Movies\Movies.csproj]
C:\Users\dharm\tmp\Movies\Microsoft.NET.Sdk.Razor.SourceGenerators\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Pages_Movies_Edit_cshtml.g.cs(439,23): error CS0234: The type or namespace name 'Pages' does not exist in the namespace 'Movies.Pages.Movies' (are you missing an assembly reference?) [C:\Users\dharm\tmp\Movies\Movies.csproj]
C:\Users\dharm\tmp\Movies\Microsoft.NET.Sdk.Razor.SourceGenerators\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Pages_Movies_Index_cshtml.g.cs(265,88): error CS0234: The type or namespace name 'Pages' does not exist in the namespace 'Movies.Pages.Movies' (are you missing an assembly reference?) [C:\Users\dharm\tmp\Movies\Movies.csproj]
C:\Users\dharm\tmp\Movies\Microsoft.NET.Sdk.Razor.SourceGenerators\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Pages_Movies_Details_cshtml.g.cs(185,88): error CS0234: The type or namespace name 'Pages' does not exist in the namespace 'Movies.Pages.Movies' (are you missing an assembly reference?) [C:\Users\dharm\tmp\Movies\Movies.csproj]
C:\Users\dharm\tmp\Movies\Microsoft.NET.Sdk.Razor.SourceGenerators\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Pages_Movies_Index_cshtml.g.cs(266,23): error CS0234: The type or namespace name 'Pages' does not exist in the namespace 'Movies.Pages.Movies' (are you missing an assembly reference?) [C:\Users\dharm\tmp\Movies\Movies.csproj]
C:\Users\dharm\tmp\Movies\Microsoft.NET.Sdk.Razor.SourceGenerators\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Pages_Movies_Details_cshtml.g.cs(186,23): error CS0234: The type or namespace name 'Pages' does not exist in the namespace 'Movies.Pages.Movies' (are you missing an assembly reference?) [C:\Users\dharm\tmp\Movies\Movies.csproj]
```

# Notes

It seems that calling the project `Movies` causes an issue for the `dotnet-aspnet-codegenerator`. If for some reason, this name is not allowed, the tool should at the very least let the user know and refuse to generate the pages instead of generating the pages and ending up with a project that does not build.

**Comment by akaver** [comment]
Similar issue - scaffolding fails when model are moved into different library/assembly. Library name is not important - tried Domain and Xyz - result is same:
`dotnet aspnet-codegenerator razorpage -m Person -dc ApplicationDbContext -udl -outDir Pages/Persons --referenceScriptLibraries -f`

`Building project ...
Finding the generator 'razorpage'...
Running the generator 'razorpage'...
A type with the name Person does not exist
`

**Comment by SirElTomato** [comment]
Also having this issue when models are in a different project to the WebApp

**Comment by Rick-Anderson** [comment]
> Also having this issue when models are in a different project to the WebApp

That's reported in multiple places. Scaffolding doesn't support models in different projects.

**Comment by drewid** [comment]
Seen a lot of variation on the theme where scaffolding is not working as expected - supposedly just supposed to work.

Specifically - having an issue where the scaffolding is not working when consolidated components from a stand-alone razor lib project into another shared project.  What designation is needed to make the scaffolding function?  The only different I can see is the previous shared project (where it works) has the following:
```
  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>
```
Thanks!

**Comment by rjbullock** [comment]
Experiencing this issue as well.

**Comment by deepchoudhery** [comment]
@akaver @SirElTomato 
Issue fixed in the new [6.0.1](https://www.nuget.org/packages/Microsoft.VisualStudio.Web.CodeGeneration.Design/) package. Reopen the issue if it persists with the new package.

Thanks,
Deep

**Comment by ljm000** [comment]
> @akaver@SirElTomato新的 [6.0.1](https://www.nuget.org/packages/Microsoft.VisualStudio.Web.CodeGeneration.Design/) 程序包中修复了有关模型位于不同但引用的程序集中的问题。如果问题在新包中仍然存在，请重新打开该问题。
> 
> 谢谢，深

 

> @akaver @SirElTomato Issue fixed in the new [6.0.1](https://www.nuget.org/packages/Microsoft.VisualStudio.Web.CodeGeneration.Design/) package regarding models being in different but referenced assemblies. Reopen the issue if it persists with the new package.
> 
> Thanks, Deep

the problem still exists
https://github.com/dotnet/Scaffolding/issues/1904

**Comment by gibbonsc** [comment]
Just encountered the problem again today, going through this tutorial:

https://learn.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-6.0&tabs=visual-studio-code

If the model class name is Movie (file name Movie.cs), the aspcodenet-generator tool doesn't work.

If the class name is something else, like MovieNet6 (file name MovieNet6.cs), the aspcodenet-generator tool works.

My `dotnet --info` output shows SDK verison `6.0402`, runtime verison `10.0.19044`.

> the problem still exists [#1904](https://github.com/dotnet/Scaffolding/issues/1904)

**Comment by gBoole01** [comment]
For anyone who encounters this issue following the tutorial 

[https://learn.microsoft.com/en-us/aspnet/core/fundamentals/tools/dotnet-aspnet-codegenerator?view=aspnetcore-7.0](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/tools/dotnet-aspnet-codegenerator?view=aspnetcore-7.0)

The command given is not the correct one, the class name should also include the namespace. If you followed through, the working command is =>

`dotnet-aspnet-codegenerator razorpage -m RazorPagesMovie.Models.RazorPagesMovie -dc RazorPagesMovie.Data.RazorPagesMovieContext -udl -outDir Pages/Movies --referenceScriptLibraries -sqlite`

**Comment by wwHwo** [comment]
This problem still exist

**Comment by hameemshah** [comment]
> This problem still exist

change Movie.cs contents to :-
using System.ComponentModel.DataAnnotations;

namespace RazorPagesMovie.Models
{
    public class Movie
    {
        public int ID { get; set; }
        public string Title { get; set; } = string.Empty;

        [DataType(DataType.Date)]
        public DateTime ReleaseDate { get; set; }
        public string Genre { get; set; } = string.Empty;
        public decimal Price { get; set; }
    }
}

**Comment by deepchoudhery** [comment]
Fixed with our new cli scaffolding tool `dotnet-scaffold`, blog [here](https://devblogs.microsoft.com/dotnet/introducing-dotnet-scaffold/)

**Comment by karl1722** [comment]
> For anyone who encounters this issue following the tutorial
> 
> https://learn.microsoft.com/en-us/aspnet/core/fundamentals/tools/dotnet-aspnet-codegenerator?view=aspnetcore-7.0
> 
> The command given is not the correct one, the class name should also include the namespace. If you followed it along you have this class `Movie` =>
> 
> ```
> using System.ComponentModel.DataAnnotations;
> 
> namespace RazorPagesMovie.Models;
> 
> public class Movie
> {
>     public int Id { get; set; }
>     public string? Title { get; set; }
>     [DataType(DataType.Date)]
>     public DateTime ReleaseDate { get; set; } = DateTime.Now;
>     public string? Genre { get; set; }
>     public decimal Price { get; set; }
> }
> ```
> 
> The working command is then =>
> 
> `dotnet-aspnet-codegenerator razorpage -m RazorPagesMovie.Models.Movie -dc RazorPagesMovie.Data.RazorPagesMovieContext -udl -outDir Pages/Movies --referenceScriptLibraries -sqlite`

the complete "working" command is 

 `dotnet-aspnet-codegenerator razorpage -m RazorPagesMovie.Models.Movie -dc RazorPagesMovie.Data.RazorPagesMovieContext -udl -outDir Pages/Movies --referenceScriptLibraries **--databaseProvider** -sqlite`

(but I get the same error:

A type with the name RazorPagesMovie.Models.Movie does not exist
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
)
