### ISSUE TITLE
Error trying to scaffold Controller - Sequence contains no elements

### ISSUE THREAD

**Issue by AlbinCederblad** [dotnet/Scaffolding#1861]
I have created a new **ASP.NET Core 6 Web API** project and I'm using an existing **MYSQL** database. I managed to scaffold models and context from the database without problems.

But when i try to scaffold controller, either when using the **Add -> Controller -> API -> API Controller with actions, using Entity Framework** (in solution explorer) or using **dotnet-aspnet-codegenerator controller** command in **Package Manager Console** i get the following error:
![JrQ2y](https://user-images.githubusercontent.com/10009313/160615555-4c51c9d6-456a-4b4e-8383-cce138133686.png)

I have looked around for 2 days for solutions to this but none of them work.
Any help appreciated. I do not know if this is a bug or not, but it seems to me like it could be.

**Comment by vijayrkn** [comment]
This should be fixed in the latest version.

**Comment by JadaVonRuth** [comment]
I am still having that issue in version 6.0.10, at least it should say what it was trying to find, stacktrace like this is not exactly helpfull
